# -*- coding: utf-8 -*-
"""Hello World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5aAZ4aNUQs7TNd8YjH-OllD9pzn-9O9
"""

print('Hello World')